module.exports = {
  ParticipantPresencePrefix: 'PARTICIPANT',
  SpectatorPresencePrefix: 'SPECTATOR',
  TimeoutEventName: 'PARTICIPANT_TIMEOUT',
  ParticipantEnterEventName: 'PARTICIPANT_ENTER',
  ExitEventName: 'PARTICIPANT_EXIT',
  ParticipantsDisplayEventName: 'PARTICIPANTS_DISPLAY',
  PrivateDisplayEventName: 'PRIVATE_DISPLAY',
  UpdateContextEventName: 'UPDATE_CONTEXT',
  SpectatorsDisplayEventName: 'SPECTATORS_DISPLAY',
  PublicDisplayEventName: 'PUBLIC_DISPLAY',
  ActiveStateName: 'active',
  ParticipantPresenceEvents: ['enter', 'leave', 'update'],
  SpectatorPresenceEvents: ['enter'],
  ActionEventName: 'ACTION',
  StartEventName: 'START',
  SpectatorEnterEventName: 'SPECTATOR_ENTER',
  UpdateContextEventName:  'UPDATE_CONTEXT',
  CreateEventEventName: 'CREATE_EVENT',
  ImagesDirPath: 'assets/images',
  CssDirPath: 'assets/css',
  PugSuffix: '.pug'
}
