module.exports = {
  TimeoutEventName: 'PARTICIPANT_TIMEOUT',
  ExitEventName: 'PARTICIPANT_EXIT',
  UpdateContextEventName: 'UPDATE_CONTEXT',
  CssUrlMessageType: 'CSS_URL',
  PrivateDisplayEventName: 'PRIVATE_DISPLAY',
  ParticipantsDisplayEventName: 'PARTICIPANTS_DISPLAY',
  SpectatorsDisplayEventName: 'SPECTATORS_DISPLAY',
  PublicDisplayEventName: 'PUBLIC_DISPLAY',
  ActiveStateName: 'active',
  ParticipantPresencePrefix: 'PARTICIPANT',
  SpectatorPresencePrefix: 'SPECTATOR',
  SpectatorPresenceEvents: ['enter', 'leave'],
  ActionEventName: 'ACTION',
  ParticipantEnterEventName: 'PARTICIPANT_ENTER',
  UpdateContextEventName:  'UPDATE_CONTEXT',
  CreateEventEventName: 'CREATE_EVENT',
  ImagesDirPath: 'assets/images',
  CssDirPath: 'assets/css',
}
